---
- apt_repository:
    repo: 'ppa:bitcoin/bitcoin'

- name: Install bitcoind
  apt:
    name: bitcoind
    update_cache: yes
- name: Data path
  file: path={{ btc_data }} state=directory owner={{ deployer_user.name }}

- name: Place bitcoind init script
  template:
    src: bitcoind.init.j2
    dest: /etc/init.d/bitcoind
    mode: u=rwx,g=r,o=r

- name: Place btccli script
  template:
    src: btccli.j2
    dest: /usr/local/bin/btccli
    mode: u=rwx,g=rx,o=rx

- name: Register with monit
  template: src=bitcoind.monit.j2
            dest=/etc/monit/conf.d/bitcoind
            mode=u=rw,g=r,o=r
  register: bitcoind_monit_config

- name: Reload Monit
  command: bash -lc "monit reload"
  when: bitcoind_monit_config.changed
