---
- name: Add erlang solutions repo
  apt:
    deb: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb

- name: Install esl-erlang
  apt:
    name: esl-erlang
    update_cache: yes

- name: Install elixir
  apt:
    name: elixir
    state: present
