---
btc_opts:
  net: "-testnet"
  port: 18333
  datadir: "{{ datadir }}"
  extras: "-prune"
  zmq:
    addr: 127.0.0.1
    port: 28332

allowed_ports:
  - "{{ btc_opts.port }}"

deployer_user:
  name: ubuntu
  groups:
    - ubuntu
    - staff
