---
btc_opts:
  net:
  port: 8333
  datadir: "{{ datadir }}"
  extras: "-txindex=1"
  zmq:
    addr: 127.0.0.1
    port: 28332

rpc_server_ip: "127.0.0.1"
rpc_client_ip: "127.0.0.1"
rpc_port: 8332

allowed_ports:
  - "{{ btc_opts.port }}"
  - "{{ rpc_port }}"

deployer_user:
  name: deployer
  groups:
    - deployer
    - staff
