---
- name: Apply env vars
  remote_user: root
  hosts: all
  roles:
    - include_env_vars

- name: Checkout latest
  remote_user: "{{ deployer_user.name }}"
  hosts:
    - nodes
    - dev
  roles:
    - git_checkout

- name: Start bitcoind
  remote_user: root
  hosts:
    - nodes
    - dev
  roles:
    - monit_activate
