---
- name: Apply common configuration
  hosts: all
  remote_user: root
  become: true
  roles:
    - common

- name: Apply bitcoin node configuration
  hosts:
    - nodes
    - dev
  remote_user: root
  become: true
  roles:
    - node
