---
- name: Apply common configuration
  hosts: all
  remote_user: root
  roles:
    - common
    - deployer_user
    - monit_install
    - git_checkout

- name: Apply bitcoin node configuration
  hosts:
    - nodes
    - dev
  remote_user: root
  roles:
    - bitcoind
