---
- name: Apply env vars
  remote_user: root
  hosts: all
  roles:
    - include_env_vars
    - rpc_setup

- name: Apply common configuration
  hosts: all
  remote_user: root
  roles:
    - common
    - deployer_user
    - ufw
    - monit_install
    - git_checkout

- name: Apply bitcoin node configuration
  hosts:
    - nodes
    - dev
  remote_user: root
  roles:
    - bitcoind

- name: Apply notifier configuration
  hosts:
    - notifiers
    - dev
  remote_user: root
  roles:
    - elixir
